name: GitHub Pages API

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    - name: Set up Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvzf ./ngrok-v3-stable-linux-amd64.tgz
        rm ./ngrok-v3-stable-linux-amd64.tgz
        chmod +x ./ngrok
        ./ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
    - name: Run Ngrok
      run: |
        tmux new-session -d -s ngrok
        tmux send-keys -t ngrok './ngrok http --domain=sharp-turtle-optionally.ngrok-free.app 5000' C-m
    - name: Run Python
      run: |
        python api.py